language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("SCS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
