language: julia
coveralls: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: false
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="MathOptInterface", rev="master"))'
